<a href="https://colab.research.google.com/github/USMS-FPK-IA-GI-2025/controle-01-numpy-and-matplotlib-iris-salmaelfadili2010/blob/main/notebooks/controle_numpy_matplotlib.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Contrôle 01 — Data Science avec NumPy et Matplotlib
**Master 1 — Intelligence Artificielle & Génie Informatique (FPK / USMS)**

Nom & Prénom :  
Filière :  
Année universitaire :

---

**Règles :**
- Bibliothèques autorisées : NumPy, Matplotlib
- Toute autre bibliothèque est interdite
- Chaque question doit être traitée dans une cellule dédiée
- Chaque résultat doit être brièvement interprété


# Partie A — Importation du Dataset, Arrays, Premières Manipulations

### A1. Importation du dataset
Importez NumPy et Matplotlib.  
Chargez le fichier `iris.csv` avec `np.genfromtxt` (`delimiter=','`, `skip_header=1`).  
Stockez les données dans un array nommé `data` et affichez sa `shape`.


In [5]:
# Votre code ici
import numpy as np
import matplotlib.pyplot as plt
data=np.genfromtxt('iris.csv',delimiter=',', skip_header=1)
print(data.shape)

(150, 5)


### A2. Séparation des features et des espèces
Séparez :
- les 4 premières colonnes numériques dans un array `features`
- la dernière colonne (espèces) dans un array `species`
Utilisez le slicing.


In [6]:
# Votre code ici
features = data[:,:4]
species =data[:,4]
print(features.shape)
print(species.shape)

(150, 4)
(150,)


### A3. Indexing
Affichez les 5 premières lignes de `features` en utilisant l’indexing.


In [7]:
# Votre code ici
print(features[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


### A4. Extraction d’une colonne
Créez un array `sepal_length` contenant uniquement la première colonne de `features`.  
Affichez sa `size` et son `dtype`.


In [8]:
# Votre code ici
sepal_length = features[:,0]
print(sepal_length.size)
print(sepal_length.dtype)

150
float64


### A5. Slicing par espèce
Utilisez le slicing pour extraire les 50 premières lignes correspondant à l’espèce *Setosa*.  
Stockez-les dans `setosa_features`.


In [10]:
# Votre code ici
setosa_features = features[0:50,:]
print(setosa_features.shape)

(50, 4)


# Partie B — Statistiques Basiques et Opérations Mathématiques

### B6. Moyenne par colonne
Calculez la moyenne de chaque colonne de `features` avec `np.mean(axis=0)`.


In [ ]:
# Votre code ici
moy=np.mean(features,axis=0)
print(moy)

### B7. Min et Max
Trouvez la valeur minimale et maximale de la longueur des pétales.


In [11]:
# Votre code ici
petales=features[:,2]
min=np.min(petales)
max=np.max(petales)
print(min)
print(max)

1.0
6.9


### B9. Normalisation
Normalisez les longueurs des pétales en les divisant par leur maximum.
Stockez le résultat dans `normalized_petals`.


In [12]:
# Votre code ici
petales=features[:,2]
normalized_petals=petales/np.max(petales)
print(normalized_petals)

[0.20289855 0.20289855 0.1884058  0.2173913  0.20289855 0.24637681
 0.20289855 0.2173913  0.20289855 0.2173913  0.2173913  0.23188406
 0.20289855 0.15942029 0.17391304 0.2173913  0.1884058  0.20289855
 0.24637681 0.2173913  0.24637681 0.2173913  0.14492754 0.24637681
 0.27536232 0.23188406 0.23188406 0.2173913  0.20289855 0.23188406
 0.23188406 0.2173913  0.2173913  0.20289855 0.2173913  0.17391304
 0.1884058  0.20289855 0.1884058  0.2173913  0.1884058  0.1884058
 0.1884058  0.23188406 0.27536232 0.20289855 0.23188406 0.20289855
 0.2173913  0.20289855 0.68115942 0.65217391 0.71014493 0.57971014
 0.66666667 0.65217391 0.68115942 0.47826087 0.66666667 0.56521739
 0.50724638 0.60869565 0.57971014 0.68115942 0.52173913 0.63768116
 0.65217391 0.5942029  0.65217391 0.56521739 0.69565217 0.57971014
 0.71014493 0.68115942 0.62318841 0.63768116 0.69565217 0.72463768
 0.65217391 0.50724638 0.55072464 0.53623188 0.56521739 0.73913043
 0.65217391 0.65217391 0.68115942 0.63768116 0.5942029  0.57971

### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [15]:
# Votre code ici
species =data[:,4]
vericolor=np.where(species == 1)
vericolor_width=features[vericolor,3]
vericolor_width_cumsum=np.cumsum(vericolor_width)
print(vericolor_width_cumsum[0:10])

[]


### B10. Somme cumulée
Calculez la somme cumulée des largeurs des pétales pour Versicolor.
Affichez les 10 premières valeurs.


In [ ]:
# Votre code ici


# Partie C — Transformations Avancées avec NumPy

### C11. Espèces uniques
Listez les espèces uniques avec `np.unique` et comptez leurs occurrences.


In [19]:
# Votre code ici
unique_species=np.unique(species,return_counts=True)
print(unique_species)


(array([nan]), array([150]))


### C12. Reshape par espèce
Transformez `features` en un array de forme `(3, 50, 4)` nommé `features_by_species`.


In [20]:
# Votre code ici
features_by_species=np.reshape(features,(3,50,4))
print(features_by_species.shape)


(3, 50, 4)


### C13. Concaténation
Concaténez horizontalement les moyennes par colonne avec un array de zéros.


In [23]:
# Votre code ici
zeros_array=np.zeros((1,4))
column_means=np.mean(features,axis=0).reshape(1,4)
result=np.hstack((zeros_array,column_means))
print(result)

[[0.         0.         0.         0.         5.84333333 3.05733333
  3.758      1.19933333]]


### C14. Data cleaning (simulation)
Simulez des valeurs NaN et remplacez-les avec `np.nan_to_num`.


In [28]:
# Votre code ici
import numpy as np
features_nan=features.copy()
features_nan[0,0]=np.nan
features_nan[10,2]=np.nan
print("avant remplecament :")
print(features_nan[[0,10],:])
features_clean=np.nan_to_num(features_nan,nan=0.0)
print("apres replacement")
print(features_clean[[0,10],:])


avant remplecament :
[[nan 3.5 1.4 0.2]
 [5.4 3.7 nan 0.2]]
apres replacement
[[0.  3.5 1.4 0.2]
 [5.4 3.7 0.  0.2]]


### C15. Broadcasting
Ajoutez 1 à toutes les valeurs de la première colonne de `features`.


In [ ]:
# Votre code ici


### C16. np.where
Créez un array binaire indiquant si la longueur des pétales est supérieure à 4.0.


In [ ]:
# Votre code ici


# Partie D — Visualisation avec Matplotlib (Plots Simples)

### D17. Line plot
Line plot des longueurs des sépales pour les 50 premières fleurs.


In [ ]:
# Votre code ici


### D18. Scatter plot
Scatter plot : longueur vs largeur des pétales.


In [ ]:
# Votre code ici


### D19. Bar chart
Bar chart des moyennes des quatre caractéristiques.


In [ ]:
# Votre code ici


### D20. Histogram
Histogramme de la largeur des sépales (10 bins).


In [ ]:
# Votre code ici


### D21. Boxplot par espèce
Boxplot des longueurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie E — Visualisations Avancées

### E22. Subplots comparatifs
Deux scatter plots côte à côte : Setosa vs Versicolor.


In [ ]:
# Votre code ici


### E23. Grille 2x2
Histogrammes des 4 caractéristiques avec `plt.subplots(2,2)`.


In [ ]:
# Votre code ici


### E24. Bar chart avec error bars
Moyennes par espèce avec écart-type.


In [ ]:
# Votre code ici


### E25. Scatter coloré par espèce
Scatter plot avec couleurs par espèce.


In [ ]:
# Votre code ici


### E26. Line plot superposé
Cumsum des largeurs des pétales par espèce.


In [ ]:
# Votre code ici


# Partie F — Mini-Analyse Finale

### F27. Corrélations
Calculez la matrice de corrélation avec `np.corrcoef`.


In [ ]:
# Votre code ici


### F28. Visualisation des corrélations
Visualisez les corrélations sous forme de bar chart ou scatter.


In [ ]:
# Votre code ici


### F29. Variance par espèce
Identifiez l’espèce avec la plus grande variance globale et visualisez ses distributions.


In [ ]:
# Votre code ici


### F30. Conclusion
Rédigez une conclusion contenant **3 insights** issus de votre analyse.


1) ...
2) ...
3) ...